// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: readcommend.proto

package readcommend

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	YearPublished uint32                 `protobuf:"varint,3,opt,name=yearPublished,proto3" json:"yearPublished,omitempty"`
	Rating        float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Pages         uint32                 `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_readcommend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetYearPublished() uint32 {
	if x != nil {
		return x.YearPublished
	}
	return 0
}

func (x *Book) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Book) GetPages() uint32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_readcommend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{1}
}

func (x *Author) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Author) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_readcommend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{2}
}

func (x *Genre) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genre) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Era struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MinYear       uint32                 `protobuf:"varint,3,opt,name=minYear,proto3" json:"minYear,omitempty"`
	MaxYear       uint32                 `protobuf:"varint,4,opt,name=maxYear,proto3" json:"maxYear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Era) Reset() {
	*x = Era{}
	mi := &file_readcommend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Era) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Era) ProtoMessage() {}

func (x *Era) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Era.ProtoReflect.Descriptor instead.
func (*Era) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{3}
}

func (x *Era) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Era) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Era) GetMinYear() uint32 {
	if x != nil {
		return x.MinYear
	}
	return 0
}

func (x *Era) GetMaxYear() uint32 {
	if x != nil {
		return x.MaxYear
	}
	return 0
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MinPages      uint32                 `protobuf:"varint,3,opt,name=minPages,proto3" json:"minPages,omitempty"`
	MaxPages      uint32                 `protobuf:"varint,4,opt,name=maxPages,proto3" json:"maxPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_readcommend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{4}
}

func (x *Size) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Size) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Size) GetMinPages() uint32 {
	if x != nil {
		return x.MinPages
	}
	return 0
}

func (x *Size) GetMaxPages() uint32 {
	if x != nil {
		return x.MaxPages
	}
	return 0
}

type GetGenresParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenresParams) Reset() {
	*x = GetGenresParams{}
	mi := &file_readcommend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenresParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenresParams) ProtoMessage() {}

func (x *GetGenresParams) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenresParams.ProtoReflect.Descriptor instead.
func (*GetGenresParams) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{5}
}

type GetErasParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErasParams) Reset() {
	*x = GetErasParams{}
	mi := &file_readcommend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErasParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasParams) ProtoMessage() {}

func (x *GetErasParams) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasParams.ProtoReflect.Descriptor instead.
func (*GetErasParams) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{6}
}

type GetSizesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizesParams) Reset() {
	*x = GetSizesParams{}
	mi := &file_readcommend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizesParams) ProtoMessage() {}

func (x *GetSizesParams) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizesParams.ProtoReflect.Descriptor instead.
func (*GetSizesParams) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{7}
}

type GetAuthorsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorsParams) Reset() {
	*x = GetAuthorsParams{}
	mi := &file_readcommend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorsParams) ProtoMessage() {}

func (x *GetAuthorsParams) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorsParams.ProtoReflect.Descriptor instead.
func (*GetAuthorsParams) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{8}
}

type GetBooksParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       *string                `protobuf:"bytes,1,opt,name=authors,proto3,oneof" json:"authors,omitempty"`
	Genres        *string                `protobuf:"bytes,2,opt,name=genres,proto3,oneof" json:"genres,omitempty"`
	MinPages      *uint32                `protobuf:"varint,3,opt,name=minPages,json=min-pages,proto3,oneof" json:"minPages,omitempty"`
	MaxPages      *uint32                `protobuf:"varint,4,opt,name=maxPages,json=max-pages,proto3,oneof" json:"maxPages,omitempty"`
	MinYear       *uint32                `protobuf:"varint,5,opt,name=minYear,json=min-year,proto3,oneof" json:"minYear,omitempty"`
	MaxYear       *uint32                `protobuf:"varint,6,opt,name=maxYear,json=max-year,proto3,oneof" json:"maxYear,omitempty"`
	Limit         *uint32                `protobuf:"varint,7,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksParams) Reset() {
	*x = GetBooksParams{}
	mi := &file_readcommend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksParams) ProtoMessage() {}

func (x *GetBooksParams) ProtoReflect() protoreflect.Message {
	mi := &file_readcommend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksParams.ProtoReflect.Descriptor instead.
func (*GetBooksParams) Descriptor() ([]byte, []int) {
	return file_readcommend_proto_rawDescGZIP(), []int{9}
}

func (x *GetBooksParams) GetAuthors() string {
	if x != nil && x.Authors != nil {
		return *x.Authors
	}
	return ""
}

func (x *GetBooksParams) GetGenres() string {
	if x != nil && x.Genres != nil {
		return *x.Genres
	}
	return ""
}

func (x *GetBooksParams) GetMinPages() uint32 {
	if x != nil && x.MinPages != nil {
		return *x.MinPages
	}
	return 0
}

func (x *GetBooksParams) GetMaxPages() uint32 {
	if x != nil && x.MaxPages != nil {
		return *x.MaxPages
	}
	return 0
}

func (x *GetBooksParams) GetMinYear() uint32 {
	if x != nil && x.MinYear != nil {
		return *x.MinYear
	}
	return 0
}

func (x *GetBooksParams) GetMaxYear() uint32 {
	if x != nil && x.MaxYear != nil {
		return *x.MaxYear
	}
	return 0
}

func (x *GetBooksParams) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

var File_readcommend_proto protoreflect.FileDescriptor

const file_readcommend_proto_rawDesc = "" +
	"\n" +
	"\x11readcommend.proto\x12\vreadcommend\x1a\x1cgoogle/api/annotations.proto\"\x80\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12$\n" +
	"\ryearPublished\x18\x03 \x01(\rR\ryearPublished\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\rR\x05pages\"R\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\"-\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"_\n" +
	"\x03Era\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aminYear\x18\x03 \x01(\rR\aminYear\x12\x18\n" +
	"\amaxYear\x18\x04 \x01(\rR\amaxYear\"d\n" +
	"\x04Size\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bminPages\x18\x03 \x01(\rR\bminPages\x12\x1a\n" +
	"\bmaxPages\x18\x04 \x01(\rR\bmaxPages\"\x11\n" +
	"\x0fGetGenresParams\"\x0f\n" +
	"\rGetErasParams\"\x10\n" +
	"\x0eGetSizesParams\"\x12\n" +
	"\x10GetAuthorsParams\"\xbe\x02\n" +
	"\x0eGetBooksParams\x12\x1d\n" +
	"\aauthors\x18\x01 \x01(\tH\x00R\aauthors\x88\x01\x01\x12\x1b\n" +
	"\x06genres\x18\x02 \x01(\tH\x01R\x06genres\x88\x01\x01\x12 \n" +
	"\bminPages\x18\x03 \x01(\rH\x02R\tmin-pages\x88\x01\x01\x12 \n" +
	"\bmaxPages\x18\x04 \x01(\rH\x03R\tmax-pages\x88\x01\x01\x12\x1e\n" +
	"\aminYear\x18\x05 \x01(\rH\x04R\bmin-year\x88\x01\x01\x12\x1e\n" +
	"\amaxYear\x18\x06 \x01(\rH\x05R\bmax-year\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\a \x01(\rH\x06R\x05limit\x88\x01\x01B\n" +
	"\n" +
	"\b_authorsB\t\n" +
	"\a_genresB\v\n" +
	"\t_minPagesB\v\n" +
	"\t_maxPagesB\n" +
	"\n" +
	"\b_minYearB\n" +
	"\n" +
	"\b_maxYearB\b\n" +
	"\x06_limit2\xc5\x03\n" +
	"\x12ReadCommendService\x12S\n" +
	"\bGetBooks\x12\x1b.readcommend.GetBooksParams\x1a\x11.readcommend.Book\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/books0\x01\x12W\n" +
	"\tGetGenres\x12\x1c.readcommend.GetGenresParams\x1a\x12.readcommend.Genre\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/genres0\x01\x12[\n" +
	"\n" +
	"GetAuthors\x12\x1d.readcommend.GetAuthorsParams\x1a\x13.readcommend.Author\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/authors0\x01\x12S\n" +
	"\bGetSizes\x12\x1b.readcommend.GetSizesParams\x1a\x11.readcommend.Size\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/sizes0\x01\x12O\n" +
	"\aGetEras\x12\x1a.readcommend.GetErasParams\x1a\x10.readcommend.Era\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/eras0\x01B'Z%github.com/BastianEscaich/readcommendb\x06proto3"

var (
	file_readcommend_proto_rawDescOnce sync.Once
	file_readcommend_proto_rawDescData []byte
)

func file_readcommend_proto_rawDescGZIP() []byte {
	file_readcommend_proto_rawDescOnce.Do(func() {
		file_readcommend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_readcommend_proto_rawDesc), len(file_readcommend_proto_rawDesc)))
	})
	return file_readcommend_proto_rawDescData
}

var file_readcommend_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_readcommend_proto_goTypes = []any{
	(*Book)(nil),             // 0: readcommend.Book
	(*Author)(nil),           // 1: readcommend.Author
	(*Genre)(nil),            // 2: readcommend.Genre
	(*Era)(nil),              // 3: readcommend.Era
	(*Size)(nil),             // 4: readcommend.Size
	(*GetGenresParams)(nil),  // 5: readcommend.GetGenresParams
	(*GetErasParams)(nil),    // 6: readcommend.GetErasParams
	(*GetSizesParams)(nil),   // 7: readcommend.GetSizesParams
	(*GetAuthorsParams)(nil), // 8: readcommend.GetAuthorsParams
	(*GetBooksParams)(nil),   // 9: readcommend.GetBooksParams
}
var file_readcommend_proto_depIdxs = []int32{
	9, // 0: readcommend.ReadCommendService.GetBooks:input_type -> readcommend.GetBooksParams
	5, // 1: readcommend.ReadCommendService.GetGenres:input_type -> readcommend.GetGenresParams
	8, // 2: readcommend.ReadCommendService.GetAuthors:input_type -> readcommend.GetAuthorsParams
	7, // 3: readcommend.ReadCommendService.GetSizes:input_type -> readcommend.GetSizesParams
	6, // 4: readcommend.ReadCommendService.GetEras:input_type -> readcommend.GetErasParams
	0, // 5: readcommend.ReadCommendService.GetBooks:output_type -> readcommend.Book
	2, // 6: readcommend.ReadCommendService.GetGenres:output_type -> readcommend.Genre
	1, // 7: readcommend.ReadCommendService.GetAuthors:output_type -> readcommend.Author
	4, // 8: readcommend.ReadCommendService.GetSizes:output_type -> readcommend.Size
	3, // 9: readcommend.ReadCommendService.GetEras:output_type -> readcommend.Era
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_readcommend_proto_init() }
func file_readcommend_proto_init() {
	if File_readcommend_proto != nil {
		return
	}
	file_readcommend_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readcommend_proto_rawDesc), len(file_readcommend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_readcommend_proto_goTypes,
		DependencyIndexes: file_readcommend_proto_depIdxs,
		MessageInfos:      file_readcommend_proto_msgTypes,
	}.Build()
	File_readcommend_proto = out.File
	file_readcommend_proto_goTypes = nil
	file_readcommend_proto_depIdxs = nil
}
